[package]
authors = ["Vladimir Matveev <vladimir.matweev@gmail.com>"]
name = "sshc"
version = "0.0.1"

[dependencies]
clap = "2.26"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
error-chain = "0.10"

[dependencies.cursive]
version = "0.6"
default-features = false
features = ["termion-backend"]
